Database:
    CassandraCluster:
        Description: The host and port of the Cassandra cluster.
        Value: 127.0.0.1:9042
    CassandraConnections:
        Description: The number of connections to the Cassandra cluster.
        Value: 2
    CassandraKeyspace:
        Description: Keyspace to use within the Cassandra database.
        Value: test
    CassandraTableName:
        Description: Name of the table to use within the Cassandra keyspace.
        Value: usertable
    CassandraPassword:
        Description: The password for authenticating with Cassandra, if required.
        Value: ""
    CassandraUsername:
        Description: The username for authenticating with Cassandra, if required.
        Value: ""
    PasswordAuthenticator:
        Description: |-
            Enables the use of Cassandra's PasswordAuthenticator for client connections. If this is true,
            then the `CassandraUsername` and `CassandraPassword` properties must be non-empty and valid.
        Value: false
Performance:
    BatchSize:
        Description: The number of operations to batch together in a single transaction or request.
        Value: 1
    DataIntegrity:
        Description: Whether to perform data integrity checks during operations.
        Value: false
    DropData:
        Description: Enables dropping any pre-existing database data upon startup.
        Value: false
    FieldCount:
        Description: The number of fields (columns) to include in a database table or a data model.
        Value: 10
    FieldLength:
        Description: The fixed length of data to store in each field of the database.
        Value: 100
    FieldLengthDistribution:
        Description: The type of distribution used to vary the length of fields in data records.
        Value: constant
    InsertCount:
        Description: The total number of records to insert during the workload execution.
        Value: 10000
    InsertionRetryInterval:
        Description: The time in seconds to wait before retrying a failed insert operation.
        Value: 3
    InsertionRetryLimit:
        Description: The maximum number of retry attempts for a failed insert operation.
        Value: 0
    MaxExecutionTime:
        Description: The maximum allowed time for the benchmark to run before it is forcibly stopped.
        Value: 0
    MaxScanLength:
        Description: The maximum number of records to scan in a single operation.
        Value: 1000
    MinScanLength:
        Description: The minimum number of records to scan in a single operation.
        Value: 1
    OperationCount:
        Description: The total number of operations to perform during the workload execution.
        Value: 10000
    RecordCount:
        Description: ""
        Value: 0
    ThreadCount:
        Description: The number of concurrent threads to use when executing the workload.
        Value: 200
    WarmUpTime:
        Description: The duration in seconds to run the workload before measurement begins.
        Value: 0
    VirtualNodes:
        Description: The number of virtual nodes to simulate or use in the execution of the workload.
        Value: 500
Workload:
    Workload:
        Description: The name of the workload to be executed.
        Value: ""
    Command:
        Description: The specific command to run as part of the workload.
        Value: ""
    DoTransactions:
        Description: Indicates whether transactions should be executed.
        Value: false
    ExponentialFrac:
        Description: The fraction of the exponential function used for generating workload distributions.
        Value: 0.8571428571
    ExponentialPercentile:
        Description: The target percentile for the exponential distribution when generating workloads.
        Value: 95
    HotspotDataFraction:
        Description: The fraction of data that will be considered 'hot' for generating hotspots in the workload.
        Value: 0.2
    HotspotOpnFraction:
        Description: The fraction of operations that will be focused on the 'hot' data.
        Value: 0.8
    InsertOrder:
        Description: The order in which records are inserted, which can be 'hashed' or another specified order.
        Value: hashed
    InsertProportion:
        Description: The proportion of insert operations in the workload.
        Value: 0
    InsertStart:
        Description: The starting point for insert operations in the workload.
        Value: 10000
    KeyPrefix:
        Description: The prefix to be used for keys in the workload.
        Value: user
    ReadAllFields:
        Description: Indicates whether all fields should be read in read operations.
        Value: true
    ReadModifyWriteProportion:
        Description: The proportion of read-modify-write operations in the workload.
        Value: 0
    ReadProportion:
        Description: The proportion of read operations in the workload.
        Value: 0.95
    RequestDistribution:
        Description: The distribution of request types in the workload, such as 'uniform'.
        Value: uniform
    ScanLengthDistribution:
        Description: The distribution used to determine scan lengths in scan operations.
        Value: uniform
    ScanProportion:
        Description: The proportion of scan operations in the workload.
        Value: 0
    UpdateProportion:
        Description: The proportion of update operations in the workload.
        Value: 0.05
    WriteAllFields:
        Description: Indicates whether all fields should be written in write operations.
        Value: false
Measurements:
    MeasurementType:
        Description: Specifies the type of measurement for performance metrics, e.g., 'histogram'.
        Value: histogram
    MeasurementRawOutputFile:
        Description: The file path where raw measurement data will be output, if any.
        Value: ""
    HistogramPercentilesExport:
        Description: Indicates whether percentile data should be exported from histogram measurements.
        Value: false
    HistogramPercentilesExportFilepath:
        Description: The directory path where histogram percentile data files are to be saved.
        Value: ./
    FieldLengthHistogramFile:
        Description: The file path of the histogram file that defines the distribution of field lengths.
        Value: hist.txt
    TargetOperationsPerSec:
        Description: The target number of operations per second that the workload should aim to achieve.
        Value: 500
    ZeroPadding:
        Description: The amount of zero-padding for numeric fields, ensuring a fixed width representation.
        Value: 1
Logging:
    DebugPprof:
        Description: The address to bind the pprof debugging server to, for profiling and debugging purposes.
        Value: :6060
    Label:
        Description: A label used to tag log entries for easier filtering and identification.
        Value: ""
    LogInterval:
        Description: The interval, in seconds, at which log entries should be written to the log output.
        Value: 10
    OutputStyle:
        Description: Defines the formatting style for the log output, such as 'json', 'plain', etc.
        Value: ""
    Silence:
        Description: If set to true, suppresses the output of logs to the console or log files.
        Value: true
    Status:
        Description: A field to log the current status of the application.
        Value: ""
    Verbose:
        Description: Enables verbose logging for debugging purposes.
        Value: false
